language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '7'
  - '6'
before_script:
  - npm install -g bower polymer-cli lighthouse
  - bower install
script:
  - lighthouse --chrome-flags="--disable-gpu --headless" https://google.com